//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI
    {
        public int AIID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> Breed { get; set; }
        public string BullID { get; set; }
        public string AIOperator { get; set; }
        public Nullable<System.DateTime> ExpectedDueDate { get; set; }
        public Nullable<bool> Born { get; set; }
    }
}
