//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int AnimalId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TagNo { get; set; }
        public string Species { get; set; }
        public string Sex { get; set; }
        public string Breed { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string OwnershipStatus { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Origin { get; set; }
    }
}
