//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birth
    {
        public int BirthId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TagNo { get; set; }
        public string MotherTagNo { get; set; }
        public string SireTagNo { get; set; }
        public Nullable<bool> Difficult { get; set; }
        public string Notes { get; set; }
    }
}
