//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Death
    {
        public int DeathId { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> UserId { get; set; }
        [Required]
        public Nullable<System.DateTime> DOD { get; set; }
        [Required]
        public string Cause { get; set; }
        public string Notes { get; set; }
    }
}
