//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MartPrice
    {
        public int ID { get; set; }
        public string Breed { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
