//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TagNo { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateBought { get; set; }
        public string BoughtFrom { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
