//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TreatmentId { get; set; }
        public Nullable<int> UserMedicineID { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> DosageAmount { get; set; }
        public string PrescribingVet { get; set; }
        public string Administrator { get; set; }
    }
}
