//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMedicine
    {
        public int UserMedicineID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<int> BottleSize { get; set; }
        public string SuppliedBy { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string Notes { get; set; }
    }
}
